name: Code

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Format
        run: yarn format

  dist:
    name: Verify committed dist directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Calculate hash of committed `dist` directory
        run: echo "COMMITTED_HASH=${{ hashFiles('./dist/**') }}" >> $GITHUB_ENV

      - run: yarn install

      - name: Calculate expected hash of `dist` directory
        run: |
          rm -rf dist && yarn run build
          echo "EXPECTED_HASH=${{ hashFiles('./dist/**') }}" >> $GITHUB_ENV

      - name: Compare committed and expected hashes
        run: |
          echo "COMMITTED_HASH: ${{ env.COMMITTED_HASH }}"
          echo "EXPECTED_HASH: ${{ env.EXPECTED_HASH }}"

          export RESULT=$(expr "${{ env.COMMITTED_HASH }}" != "${{ env.EXPECTED_HASH }}")
          echo "RESULT: $RESULT"
          exit $RESULT
