name: NPM Package Publish

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  test:
    name: Build, test and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@keep-network"

      - name: Setup git credentials
        run: |
          git config user.name @thesis-heimdall
          git config user.email thesis-heimdall@users.noreply.github.com
          echo "TEST" >> test.txt
          git add test.txt
          git commit -m "TEST [skip ci]"

      - name: Push git commit
        run: git push
